version: '3'

services:
  db:
    image: postgres
    container_name: scladdv_postgress
    ports:
      - '54321:5432'
    environment:
      POSTGRES_DB: 'skladdv'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_INITDB_ARGS: "-A md5"
    restart: always
    volumes:
      - ./db_skladdv:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11.0-rc.1-management
    container_name: scladdv_rabbitmq
    expose:
      - "15672"
      - "5672"
    restart: always

  redis:
    image: redis
    container_name: scladdv_redis
    restart: always
    expose:
      - "6379"

  web:
    container_name: skladdv_web_dev
    build: .
    environment:
      - DEBUG=True
      - POSTGRES_IP=db
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    links:
     - db
    command: ./run.sh
    volumes:
      - .:/scladdv
    ports:
      - '80:80'
    depends_on:
      - db

